spring:
  profiles:
    active: local
  application:
    name: ms-alarmas
  datasource:
    url: jdbc:postgresql://localhost:5433/bd_alarmas
    username: appuser
    password: apppass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-ecmx143cjy36oshj.us.auth0.com/
server:
  port: 8082

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    doc-expansion: none
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs