spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-ecmx143cjy36oshj.us.auth0.com/
  application:
    name: ms-reportes
  datasource:
    url: jdbc:postgresql://localhost:5431/bd_reportes
    username: appuser
    password: apppass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  profiles:
    active: local
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8081

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    doc-expansion: none
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs