spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-ecmx143cjy36oshj.us.auth0.com/
  application:
    name: ms-reportes
  datasource:
    url: jdbc:postgresql://localhost:5431/bd_reportes
    username: appuser
    password: apppass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

server:
  port: 8081